a = open("24_18186.txt").readline()
a = a.replace("A", "*")
a = a.replace("E", "*")
a = a.replace("C", "-")
a = a.replace("B", "-")
a = a.replace("D", "-")
a = a.replace("G", "-")
a = a.replace("H", "-")
a = a.replace("F", "-")
a = a.replace("--*", "+++")
a = a.replace("*", "-")

a = a.split("+++")
print(len(max(a, key=len)))
