a = open("24_59849.txt").readline()
#0123456789ABCDEFGHIJKLMNOP
alphabet = sorted("0123456789qwertyuiopasdfghjklzxcvbnm")
print(alphabet,len(alphabet))
a = a.replace("R", " ")
a = a.replace("S", " ")
a = a.replace("T", " ")
a = a.replace("G", " ")
a = a.replace("U", " ")
a = a.replace("V", " ")
a = a.replace("W", " ")
a = a.replace("X", " ")
a = a.replace("Y", " ")
a = a.replace("Z", " ")
a = a.split()
print(len(max(a, key=len)))
